import type { Metadata } from "next";
import "@/app/globals.css";
import { ReactNode } from "react";
import Layout from "@/core/components/layout/Layout";

export const metadata: Metadata = {
  title: "Project | shad cn ",
  description: "Generated by create next app",
};

interface RootProps {
  readonly children: ReactNode;
}

export default function RootLayout({ children }: RootProps) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
